In [2]:
import numpy as np

In [6]:
x=np.random.random(15)
print(x)
x.sort()
print(x)

[0.37482091 0.05953103 0.65662165 0.16643275 0.59656035 0.44492388
 0.21983514 0.72956233 0.39817441 0.424256   0.48611408 0.16782742
 0.70674097 0.72764579 0.78296446]
[0.05953103 0.16643275 0.16782742 0.21983514 0.37482091 0.39817441
 0.424256   0.44492388 0.48611408 0.59656035 0.65662165 0.70674097
 0.72764579 0.72956233 0.78296446]


In [8]:
v = np.arange(3,18)
v

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [12]:
a = np.array([0,1,2,3,4,5])
b=np.array([4,5,6,7,8])
np.intersect1d(a,b)

array([4, 5])

In [15]:
f =np.pad(a,pad_width=1,mode="constant",constant_values=5)
f

array([5, 0, 1, 2, 3, 4, 5, 5])

In [16]:
x=np.zeros((6,6),dtype =int)
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

In [5]:
x= np.random.random((4,4))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)
#can also use normalize function( from sklearn.preprocessing import normalize)

Original Array:
[[0.26093541 0.74994547 0.70898768 0.16774694]
 [0.85530446 0.99813368 0.9435254  0.09295235]
 [0.03371309 0.26501955 0.27194728 0.74732059]
 [0.05316312 0.01281993 0.91719307 0.76419343]]
After normalization:
[[0.25181367 0.74811251 0.70654423 0.15723622]
 [0.85504189 1.         0.94457777 0.0813268 ]
 [0.02120458 0.25595869 0.26298969 0.74544851]
 [0.04094451 0.         0.91785296 0.76257283]]


In [26]:
g=np.datetime64("today","D")
g

numpy.datetime64('2021-08-06')

In [27]:
yesterday_Date=g-np.timedelta64(1,"D")
yesterday_Date

numpy.datetime64('2021-08-05')

Create a 5x5 matrix with row values ranging from 0 to -4. (0,-1,-2 etc)

In [4]:
Z = np.zeros((5,5))
Z += np.arange(-4,1)
print(Z)

[[-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]
 [-4. -3. -2. -1.  0.]]
